#!/bin/bash

# just a command to launch urxvt with bulbasaur background
urxvt -hold -pixmap ~/.pokemon/bulbasaur.jpg \
-e bash \
-c "printf '\033]708;rgb:77/ac/98\007'; bash" # clean up the terminal padding
