#!/bin/bash

# just a command to launch urxvt with pikachu background
urxvt -hold -pixmap ~/.pokemon/pikachu.jpg \
-e bash \
-c "printf '\033]708;rgb:f7/de/82\007'; bash" # clean up the terminal padding
